accounts/urls.py
from django.urls import path

from . import views

app_name='accounts'

urlpatterns = [
    path('signup/',views.signup_view, name="signup"),
    path('login/',views.login_view, name="login"),
    path('logout/',views.logout_view, name="logout"),
]

campaigns/urls.py
from django.urls import path

from . import views


app_name = 'main'

urlpatterns = [
    path('campaigns/', views.campaigns, name="campaign_list"),
    path('contacts/', views.contacts, name="contact_list"),
    path('campaigns/new/', views.new_campaign, name="new_campaign"),
    path('campaigns/new/startemail/', views.new_email, name="new_email"),
    path('contacts/new/', views.new_contact, name="new_contact"),
    path('contacts/upload/', views.uploadcontacts, name="upload_contacts"),
    path('authorize/<slug>/', views.click_page, name="click_page"),
]

phishtry/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('accounts/', include('accounts.urls')),
    path('main/', include('campaigns.urls')),
    path('', views.homepage, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campaigns/models.py
import uuid
from datetime import timedelta

from django.db import models
from django.contrib.auth.models import User


class Campaign(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return self.title

#Not implemented yet
class Group(models.Model):
    name = models.CharField(max_length=50)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    campaign = models.ForeignKey(Campaign, default=None, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-name"]

    def __str__(self):
        return self.name

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    link_id = models.SlugField(default=uuid.uuid4)
    campaign = models.ForeignKey(Campaign, default=None, related_name='contacts', \
        on_delete=models.CASCADE, blank=True, null=True)
    group = models.ForeignKey(Group, default=None, \
        on_delete=models.CASCADE, blank=True, null=True)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    clicked = models.BooleanField(default=False)
    email_sent = models.BooleanField(default=False)
    date_sent = models.DateTimeField(auto_now_add=False, blank=True, null=True)
    date_clicked = models.DateTimeField(auto_now_add=False, blank=True, null=True)

    def passed_time(self):
        sent = self.date_sent
        clickdate = self.date_clicked
        result = clickdate - sent
        return timedelta(seconds=result.seconds)

    class Meta:
        ordering = ["-name"]

    def __str__(self):
        return self.name

class ContactUpload(models.Model):
    textfile = models.FileField()

class EmailLog(models.Model):
    campaign = models.ForeignKey(Campaign, default=None, on_delete=models.CASCADE)
    contacts = models.ManyToManyField(Contact)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

campaigns/forms.py
#from django.contrib.auth.models import User
from django import forms
from . import models

class CreateContact(forms.ModelForm):
    class Meta:
        model = models.Contact
        fields = ['name', 'email']

class CampaignForm(forms.ModelForm):
    class Meta:
        model = models.Campaign
        fields = ['title']

class UploadForm(forms.Form):
    textfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

class NewEmail(forms.ModelForm):

    class Meta:
        model = models.EmailLog
        fields = ['contacts', 'body']

    def __init__(self, user, *args, **kwargs):
        super(NewEmail, self).__init__(*args, **kwargs)
        self.fields['contacts'] = forms.ModelMultipleChoiceField( \
            widget=forms.CheckboxSelectMultiple, \
            queryset=models.Contact.objects.filter(added_by=user))

campaigns/views.py
import os
from datetime import datetime
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Case, When
from django.core.mail import send_mail
from django_tables2 import RequestConfig

from .forms import CreateContact, UploadForm, CampaignForm, NewEmail
from .models import Contact, Campaign, ContactUpload, EmailLog
from .tables import ContactTable, CampaignTable

def click_page(request, slug):
    contact = Contact.objects.get(link_id=slug)
    contact.clicked = True
    contact.date_clicked = datetime.now()
    contact.save()
    return render(request, 'campaigns/click_page.html', {'contact':contact})

@login_required(login_url="/accounts/login/")
def campaigns(request):
    campaigns_contacts = Campaign.objects.all() \
        .filter(author=request.user).annotate(contact_count=Count('contacts', distinct=True)) \
        .annotate(sent_mails=Count(Case(When(contacts__email_sent=True, then='contacts')))) \
        .annotate(click_count=Count(Case(When(contacts__clicked=True, then='contacts'))))
    table = CampaignTable(campaigns_contacts)
    RequestConfig(request).configure(table)
    return render(request, 'campaigns/campaign_list.html', {'table':table})

@login_required(login_url="/accounts/login/")
def new_campaign(request):
    template_name = 'campaigns/new_campaign.html'
    if request.method == 'POST':
        form = CampaignForm(request.POST)
        if form.is_valid():
            campaign = form.save(commit=False)
            campaign.author = request.user
            campaign.save()
            return redirect('main:new_email')
    else:
        form = CampaignForm()
    return render(request, template_name, {'form':form})

@login_required(login_url="/accounts/login/")
def contacts(request):
    contacts_count = Contact.objects.all() \
        .filter(added_by=request.user)
    table = ContactTable(contacts_count)
    RequestConfig(request).configure(table)
    return render(request, 'campaigns/contact_list.html', {'table':table})

@login_required(login_url="/accounts/login/")
def new_contact(request):
    template_name = 'campaigns/new_contact.html'
    if request.method == 'POST':
        form = CreateContact(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.added_by = request.user
            contact.save()
            return redirect('main:contact_list')
    else:
        form = CreateContact()
    return render(request, template_name, {'form':form})

@login_required(login_url="/accounts/login/")
def uploadcontacts(request):
    template_name = 'campaigns/upload_contacts.html'
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            newfile = ContactUpload(textfile=request.FILES['textfile'])
            newfile.save()
            uploaded = ContactUpload.objects.first()
            uploaded.textfile.open()
            lines = uploaded.textfile.readlines()
            for line in lines:
                line = line.decode('utf-8') \
                    .replace('\n', '')[:-1].split(' <', 1)
                name = line[0]
                email = line[1]
                Contact.objects.create(name=name, email=email, added_by=request.user)
            newfile.delete()
            os.remove(os.path.join(settings.MEDIA_ROOT, uploaded.textfile.name))
            return redirect('main:contact_list')
    else:
        form = UploadForm()
    return render(request, template_name, {'form':form})

@login_required(login_url="/accounts/login/")
def new_email(request):
    template_name = 'campaigns/start_email.html'
    if request.method == 'POST':
        form = NewEmail(request.user, request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.campaign = Campaign.objects.first()
            post.save()
            form.save_m2m()
            linkbase = 'http://' + request.META['HTTP_HOST']  \
                + '/main/authorize/'
            from_email = settings.DEFAULT_FROM_EMAIL
            subject = 'Test Phish-Try'
            contacts_form = EmailLog.objects.first()
            for contact in contacts_form.contacts.all():
                person = Contact.objects.get(name=contact)
                recipient_list = []
                recipient_list.append(contact.email)
                link = linkbase + contact.link_id + '/'
                message = post.body + '\n\n' + link
                send_mail(subject, message, from_email, recipient_list, fail_silently=False)
                person.campaign = post.campaign
                person.email_sent = True
                person.date_sent = datetime.now()
                person.save()
            return redirect('main:campaign_list')
    else:
        form = NewEmail(request.user)
    return render(request, template_name, {'form':form})

campaigns/templates/campaigns/campaign_list.html
{% extends "base_layout.html" %}
{% load render_table from django_tables2 %}
{% block content %}
    {% render_table table %}
{% endblock content %}
    

campaigns/templates/campaigns/click_page.html
{% load static from staticfiles %}
<head>
    <title>Phish-Try Click Page</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
</head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<div class="text-center">
    <div style="margin-top: 300 !important;">
        <p></p>
        <p></p>
        <h1>Dear {{ contact.name }}</h1>
        <p>You've clicked a link for a phishing test application.</p>
        <p>Please don't click any other links that you don't know the source of again.</p>
        <p class="author">You've been added by user: <b> {{ contact.added_by.username }} </b></p>
    </div>
</div>

campaigns/templates/campaigns/contact_list.html
{% extends "base_layout.html" %}
{% load render_table from django_tables2 %}
{% block content %}
    {% render_table table %}
    <div class="wrapper">
        <li><a href="{%url 'main:upload_contacts' %}">Upload Contacts</a></li>
        <li><a href="{%url 'main:new_contact' %}">Add Contact</a></li>
    </div>    
{% endblock content %}
    

campaigns/templates/campaigns/new_campaign.html
{% extends "base_layout.html" %}
{% block content %}
{% if user.is_authenticated %}
<div class="wrapper">
    <h1>New Campaign</h1>
    <form action="#" method="post" class="site-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% else %}
<h2>Please login/signup to continue.</h2>
{% endif %}
{% endblock content %}

    

campaigns/templates/campaigns/new_contact.html
{% extends "base_layout.html" %}


{% block content %}
{% if user.is_authenticated %}
<div class="wrapper">
    <h1>New Contact</h1>
    <form action="#" method="post" class="site-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>

{% else %}
<h2>Please login or signup to continue.</h2>
{% endif %}
    
{% endblock content %}

    

campaigns/templates/campaigns/start_email.html
{% extends "base_layout.html" %}
{% block content %}
{% if user.is_authenticated %}
<div class="wrapper">
    <h1>Start Email</h1>
    <form action="#" method="post" class="site-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% else %}
<h2>Please login or signup to continue.</h2>
{% endif %}
{% endblock content %}

    

campaigns/templates/campaigns/upload_contacts.html
{% extends "base_layout.html" %}


{% block content %}

<div class="wrapper">
    <h2>Upload Contacts</h2>
    <form action="#" method="post" class="site-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Upload"/>
    </form>
</div>


{% endblock content %}
    