accounts/urls.py
from django.urls import path

from . import views

app_name='accounts'

urlpatterns = [
    path('signup/',views.signup_view, name="signup"),
    path('login/',views.login_view, name="login"),
    path('logout/',views.logout_view, name="logout"),
]

campaigns/urls.py
from django.urls import path

from . import views


app_name = 'main'

urlpatterns = [
    path('campaigns/', views.campaigns, name="campaign_list"),
    path('contacts/', views.contacts, name="contact_list"),
    path('campaigns/new/', views.new_campaign, name="new_campaign"),
    path('campaigns/new/startemail/', views.new_email, name="new_email"),
    path('contacts/new/', views.new_contact, name="new_contact"),
    path('contacts/upload/', views.uploadcontacts, name="upload_contacts"),
    path('authorize/<slug>/', views.click_page, name="click_page"),
]

phishtry/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('accounts/', include('accounts.urls')),
    path('main/', include('campaigns.urls')),
    path('', views.homepage, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>About me</h1>
    <h2>Dogukan Atlihan</h2>
{% endblock  %}

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Phish-Try</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="logo"></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated%}
                    <li><a href="{% url 'main:contact_list' %}">Contacts</a></li>
                    <li><a href="{% url 'main:campaign_list' %}">Campaigns</a></li>
                    <li>User:&nbsp;&nbsp;<b>{{ user.get_username }}</b></li>
                    <li>
                        <form action="{% url 'accounts:logout' %}" method="post" class="logout-link">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                        <li><a href="{% url 'main:new_campaign' %}" class="highlight">New Campaign</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

templates/homepage.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="wrapper">
    <h1>Welcome to Phish-Try</h1>
    
    {% if user.is_anonymous%}       
    <h2>Please login or signup to continue.</h2>
    {% endif %}

</div>
{% endblock content %}
    
